name: Docker

on:
  workflow_call:
    inputs:
      workflow-run-id:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64-unknown-linux-musl, arm-unknown-linux-musleabi, x86_64-unknown-linux-musl]
        include:
          - arch: aarch64-unknown-linux-musl
            buildx-platform: linux/arm64
          - arch: arm-unknown-linux-musleabi
            buildx-platform: linux/arm/v7
          - arch: x86_64-unknown-linux-musl
            buildx-platform: linux/amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: netiso-srv-${{ matrix.arch }}
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ inputs.workflow-run-id }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Login to Docker Hub
      #  if: github.event_name != 'pull_request'
      #  uses: docker/login-action@v3
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/tuxuser/netiso-srv-rs
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Copy binary
        run: |
          cp ./target/${{ matrix.arch }}/release/netiso-srv .

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.buildx-platform }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

#      - name: Docker Hub Description
#        if: github.event_name != 'pull_request'
#        uses: peter-evans/dockerhub-description@v4
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#          repository: tuxuser/netiso-srv-rs
#          readme-filepath: ./README.md
#          short-description: "Alternative NetISO server for x360 netiso dashlaunch plugin"
